### ISSUE TITLE
The web site should provide a view for a range of DR versions

### ISSUE THREAD

**Issue by senesis** [cmip6dr/website#4]
The WIP and CMIP6 panel acknowldeged that modeling centers could use various versions of the DR for producing CMIP6 results, and that they will be able to publish these products accordingly.

This raises the need to maintain a way to share a copnveninet wiew of these DR versions, i.e. to share versions of this web site for various DR versions

As far as CNRM is concerned, the need starts with version DR01.00.20

**Comment by martinjuckes** [comment]
There are several aspects of the site. Providing all the spreadsheets (http://clipc-services.ceda.ac.uk/dreq/data/tabs02/cmvme_AerChemMIP_1pctCO2_3_3.xlsx etc ) is problematic with the current setup. As an interim step I can set up the variable and experiment search plus the views of the datbase records (http://clipc-services.ceda.ac.uk/dreq/u/1427806e-b574-11e6-9ed4-5404a60d96b5.html etc) for earlier versions. Would this be enough? The spreadsheets for earlier versions can be obtained from the command line.

**Comment by senesis** [comment]
We have no use of the spreadsheets. Providing the the variable and experiment search plus the full (html) views of the database records (with all links working) would be perfect.

**Comment by matthew-mizielinski** [comment]
I've thought about this previously and I have been using wget to take a copy of the html interface each time @martinjuckes releases a new version from 01.00.02 onwards (with the odd omission).

To save storage I've lately been excluding the excel files as we don't use them either; we use wrappers around dreqPy to obtain variable lists for experiments rather than the spreadsheets.

Should it be useful the command I'm using is `wget -r --reject xlsx http://clipc-services.ceda.ac.uk/dreq/index.html`

**Comment by senesis** [comment]
Thanks @matthew-mizielinski for the trick, which I will use. However, sharing a reference version of the website could also be much useful in the future discussions with, e.g. PrePARE (and ESGF publisher) developpers. This , assuming it is not too much burden on Martins' side

**Comment by matthew-mizielinski** [comment]
Agreed. I'm happy to supply my archive of previous versions if this is useful or easier than regenerating them.

**Comment by senesis** [comment]
I assume that no center will need website version before DR01.0020, which is still online and could be the first one freezed by Martin. Thanks anyway

**Comment by martinjuckes** [comment]
Frozen versions now available.
